// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_route`, `command_route`, `ensure_local_sessions_restored`, `event_receiver`, `network_name`, `parse_network`, `parse_route`, `remote_media`, `runtime`

int protocolVersion() => RustLib.instance.api.crateApiProtocolVersion();

bool routeIsAllowed({required String network, required String route}) =>
    RustLib.instance.api.crateApiRouteIsAllowed(network: network, route: route);

Future<void> connectServer({
  required String endpoint,
  required String token,
  required String deviceId,
}) => RustLib.instance.api.crateApiConnectServer(
  endpoint: endpoint,
  token: token,
  deviceId: deviceId,
);

void disconnectServer() => RustLib.instance.api.crateApiDisconnectServer();

Future<String> executeCommandJson({required String commandJson}) =>
    RustLib.instance.api.crateApiExecuteCommandJson(commandJson: commandJson);

Future<String> uploadMedia({
  required String network,
  required String accountId,
  required String route,
  required String path,
  required String filename,
  required String contentType,
}) => RustLib.instance.api.crateApiUploadMedia(
  network: network,
  accountId: accountId,
  route: route,
  path: path,
  filename: filename,
  contentType: contentType,
);

String drainEventsJson() => RustLib.instance.api.crateApiDrainEventsJson();

String listAccountsJson() => RustLib.instance.api.crateApiListAccountsJson();
